### ISSUE TITLE
config.json: no such file or directory

### ISSUE THREAD

**Issue by nsirolli** [Crandel/gmail#27]
The config.json file exists (both in `.config/mail` and in `.config/mail_checker`; you mention both locations in the readme, so I created them both), but I get an error message:

> nico@pc-sirolli ~> ls .config/mail/config.json
> .config/mail/config.json
> nico@pc-sirolli ~> ls .config/mail_checker/config.json
> .config/mail_checker/config.json
> nico@pc-sirolli ~> mail_checker
> 2024-11-21 11:54:48 ERR error during get file error="open ~/.config/mail/config.json: no such file or directory"
> nico@pc-sirolli ~> mail_checker -add
> 2024-11-21 11:55:01 ERR error during opening file error="open ~/.config/mail/config.json: no such file or directory"
> 2024-11-21 11:55:01 ERR failed to add user to config error="open ~/.config/mail/config.json: no such file or directory"

BTW, I renamed the binary file from `mail` to `mail_checker`.

**Comment by Crandel** [comment]
Thank you for feedback. I'm using this project to improve my Go skills, so it not actually prod ready, but I've tried to fix this and other configuration issues. I hope my README updates will help you to setup it. Fill free to provide more feedback, if needed.

**Comment by nsirolli** [comment]
Thanks again.

Running the binary with the `-add` flag created a folder named `~` in my home directory! With `.config/mail/config.json` inside.
